### ISSUE TITLE
String Formatting Error

### ISSUE THREAD

**Issue by anon-sportycto** [A-Kimpton/go-kimpton-dclonetracker#3]
I am getting this in my server from the bot:

```[Americas][Hardcore][Softcore] has progress: 6/6```

Instead of printing ladder/non-ladder, it is printing hardcore/softcore (incorrectly) twice.

**Comment by anon-cto** [comment]
I believe it's caused by this line of code: https://github.com/A-Kimpton/go-kimpton-dclonetracker/blob/40fc74e8231e50b625f999bed70d0e5c16c07961/d2ioscraper/state.go#L51

**Comment by A-Kimpton** [comment]
Thanks for finding that - I hadn't noticed until you pointed it out! :) +2
